from fastapi import FastAPI
import pandas as pd
import os

app = FastAPI(
    title="Mutual Fund Analytics API",
    description="API for Mutual Fund Analytics Project",
    version="1.0.0",
    contact={
        "name": "Sure Venkata Srihari",
        "email": "student@example.com"
    },
    license_info={
        "name": "MIT"
    }
)

@app.get(
    "/",
    tags=["Home"],
    summary="Home Endpoint",
    description="Returns the API status."
)
def home():
    return {
        "message": "Welcome to Mutual Fund Analytics API",
        "status": "Running"
    }


@app.get(
    "/health",
    tags=["Health"],
    summary="Health Check",
    description="Checks whether the API is healthy."
)
def health():
    return {
        "status": "Healthy"
    }


@app.get(
    "/cluster-labels",
    tags=["Analytics"],
    summary="Cluster Labels",
    description="Returns cluster labels generated by KMeans clustering."
)
def cluster_labels():

    file_path = "output/cluster_labels.csv"

    if not os.path.exists(file_path):
        return {"error": "cluster_labels.csv not found"}

    df = pd.read_csv(file_path)

    return df.to_dict(orient="records")


@app.get(
    "/portfolio-stats",
    tags=["Analytics"],
    summary="Portfolio Statistics",
    description="Returns portfolio statistics generated from clustering."
)
def portfolio_stats():

    file_path = "output/portfolio_stats.csv"

    if not os.path.exists(file_path):
        return {"error": "portfolio_stats.csv not found"}

    df = pd.read_csv(file_path)

    return df.to_dict(orient="records")